---
gateway: 192.168.11.59
netmask: 255.255.240.0
#gateway2: 192.168.132.1
#netmask2: 255.255.255.0
# VMWare default ens192
# KVM default ens3
# Libvirt default enp1s0
# Intel NUC default eno1
interface: ens2
#interface2: ens224
dns: 
  - 192.168.11.59
webserver_url: 192.168.11.59
webserver_port: 8080

# Drive to install RHCOS
# Libvirt - can be vda
install_drive: vda

# Chose the binary architecture
# x86_64 or ppc64le
arch: "x86_64"

ocp_version: 4.4.3
iso_checksum: dc1287165ff5b9d10e729c5541b616d466a9f0ed2e3380d59490503758a4cb24
iso_checksum_ppc64: ff3ef20a0c4c29022f52ad932278b9040739dc48f4062411b5a3255af863c95e
iso_name: rhcos-{{ ocp_version }}-x86_64-installer.x86_64.iso
iso_name_ppc64: rhcos-{{ ocp_version }}-ppc64le-installer.ppc64le.iso
rhcos_bios: rhcos-{{ ocp_version }}-x86_64-metal-bios.raw.gz
...
